---
title: "working"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
data = read.csv("data/stepsSleep.csv")
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
```

## R Markdown

```{r}
glimpse(data)
```



```{r}
varNames = names(data)
stepsObsByTime <- tibble(Student.ID = integer(), date = character(), time = character(), steps = integer(), asleep = integer())
for(i in 3:98) {
  for(j in 1:3100) {
    stepsObsByTime <- stepsObsByTime %>% 
      add_row(Student.ID = data[j,1],
              date = data[j,2],
              time = varNames[i],
              steps = data[j,i],
              asleep = data[j,i+96])
  }
}
```

```{r}
stepsObsByTime <- read.csv("data/stepsObsByTime.csv")
stepsObsByTime <- stepsObsByTime %>%
  mutate(time = substr(time, 2,8)) %>%
  mutate(time = as.numeric(time)) %>%
  mutate(timeOfDay = case_when(
    time < 8.0 ~ "earlyAM",
    time >= 8.0 & time < 12.0 ~ "lateAM",
    time >= 12.0 & time < 20.0 ~ "earlyPM",
    time >= 20.0 ~ "latePM"
  )) %>%
  mutate(timeOfDay = as.factor(timeOfDay)) %>%
  mutate(timeFrom2 = case_when(
    abs(time - 2) < abs(time - 26) ~ abs(time - 2),
    abs(time - 2) >= abs(time - 26) ~ abs(time - 26)
  )) %>%
  mutate(date = substr(date, 9,10)) %>%
  mutate(date = as.integer(date))
```

```{r}
logit_mod <- glm(asleep ~ steps, data = stepsObs2, family = binomial)
tidy(logit_mod)
summary(logit_mod)
```

```{r}
log_odds <- augment(logit_mod, newdata = stepsObs2) %>%
  mutate(odds = exp(.fitted)) %>%
  mutate(pred_prob = odds / (1 + odds)) %>%
  mutate(pred = case_when(
    pred_prob <= 0.5 ~ 0,
    pred_prob > 0.5 ~ 1
  ))
```





```{r}
stepsObsMN <- stepsObsByTime %>%
  filter(time == 0.00) %>%
  group_by(Student.ID) %>%
  summarize(steps = mean(steps), asleep = getmode(asleep), timeOfDay = getmode(timeOfDay), time = getmode(time))

stepsObsMNTraining <- stepsObsMN %>%
  filter(Student.ID < 81)
```

```{r}
mn_model <- glm(asleep ~ steps, data = stepsObsMNTraining, family = binomial)
tidy(mn_model)
summary(mn_model)
stepsObsMNPred <- augment(mn_model, newdata = stepsObsMN) %>%
  mutate(odds = exp(.fitted)) %>%
  mutate(pred_prob = odds / (1 + odds)) %>%
  mutate(pred = case_when(
    pred_prob <= 0.5 ~ 0,
    pred_prob > 0.5 ~ 1
  ))
```

```{r echo=FALSE}
makeModel <- function(i) {
  stepsObsTraining <- stepsObsByTime %>%
    filter(abs(time - (floor(i/4) + (i%%4)*0.15)) < 0.03) %>%
    filter(Student.ID < 80) %>%
    group_by(Student.ID) %>%
    summarize(steps = mean(steps), asleep = getmode(asleep), timeOfDay = getmode(timeOfDay), time = getmode(time))
  return(stepsObsTraining)
}


trainingDataList = list()
for(i in 0:95) {
  trainingDataList[[i+1]] <- makeModel(i)
}

models = list()
models[[1]] <- glm(asleep ~ steps, data = trainingDataList[[1]], family = binomial)

for(i in 1:95) {
  models[[i+1]] <- glm(asleep ~ steps, data = trainingDataList[[i+1]], family = binomial)
}


```

```{r}
modelParams <- tibble(time = numeric(), intercept = numeric(), steps = numeric())
for(i in 0:95) {
  modelParams <- modelParams %>%
    add_row(time = i,
            intercept = tidy(models[[i+1]]) %>% filter(term == "(Intercept)") %>% pull(estimate),
            steps = tidy(models[[i+1]]) %>% filter(term == "steps") %>% pull(estimate)
            )
}
```


```{r}
dataList = list()
for(i in 0:95) {
  dataList[[i+1]] <- stepsObsByTime %>%
    filter(abs(time - (floor(i/4) + (i%%4)*0.15)) < 0.03) %>%
    group_by(Student.ID) %>%
    summarize(steps = mean(steps), asleep = getmode(asleep), timeOfDay = getmode(timeOfDay), time = getmode(time))
}


modelPredictions <- list()
for(i in 0:95) {
  modelPredictions[[i+1]] <- augment(models[[i+1]], newdata = dataList[[i+1]]) %>%
    mutate(odds = exp(.fitted)) %>%
    mutate(pred_prob = odds / (1 + odds)) %>%
    mutate(pred = case_when(
      pred_prob <= 0.5 ~ 0,
      pred_prob > 0.5 ~ 1
    ))
}

dataListRaw <- list()
for(i in 0:95) {
  dataListRaw[[i+1]] <- stepsObsByTime %>%
    filter(abs(time - (floor(i/4) + (i%%4)*0.15)) < 0.03) %>%
    filter(Student.ID >= 80)
}

modelPredictionsRaw <- list()
for(i in 0:95) {
  cutoff <- dataListRaw[[i+1]] %>%
    summarize(mean = mean(asleep)) %>%
    pull(mean)
  
  modelPredictionsRaw[[i+1]] <- augment(models[[i+1]], newdata = dataListRaw[[i+1]]) %>%
    mutate(odds = exp(.fitted)) %>%
    mutate(pred_prob = odds / (1 + odds)) %>%
    mutate(pred = case_when(
      pred_prob <= quantile(pred_prob, 1-cutoff) ~ 0,
      pred_prob > quantile(pred_prob, 1-cutoff) ~ 1
    ))
}
```

```{r}
modelAccuracy <- list()

for(i in 0:95) {
  modelAccuracy[[i+1]] <- modelPredictionsRaw[[i+1]] %>%
    mutate(correct = abs(pred - asleep)) %>%
    summarize(percent = 1-mean(correct)) %>%
    pull(percent)
}

modelAccuracyV <- unlist(modelAccuracy)
```

```{r}
ggplot(modelParams) +
  geom_point(aes(x=time, y=intercept))

ggplot(modelParams) +
  geom_point(aes(x=time, y=steps)) +
  geom_point(aes(x=time,y=modelAccuracyV)) +
  ylim(-1,1)
```


```{r}
stepsObsTraining <- stepsObsByTime %>% 
  filter(Student.ID < 81)
dumbModel <- glm(asleep ~ steps, data = stepsObsTraining, family = binomial)

dumbModelAccuracy <- augment(dumbModel, newdata = stepsObsByTime) %>%
  mutate(odds = exp(.fitted)) %>%
  mutate(pred_prob = odds / (1 + odds)) %>%
  mutate(pred = case_when(
    pred_prob <= 0.5 ~ 0,
    pred_prob > 0.5 ~ 1
  )) %>%
  mutate(correct = abs(asleep - pred)) %>%
  summarize(percent = 1-mean(correct)) %>%
  pull(percent)
  
```